<template><h1 id="keybase-joins-zoom"><a class="header-anchor" href="#keybase-joins-zoom">#</a> Keybase joins Zoom</h1>
<p>Keybase has been acquired by Zoom, a publicly traded American company known for its online video calling solutions. After verifying the news with <a href="https://keybase.io/chris" title="Chris Coyne, co-founder of Keybase" target="_blank" rel="noopener noreferrer">one of Keybase's co-founders<OutboundLink/></a>, I was told that it was really true, with a redirect to an <a href="https://keybase.io/blog/keybase-joins-zoom" title="Keybase Blog: Keybase joins Zoom" target="_blank" rel="noopener noreferrer">official blog article<OutboundLink/></a> from the Keybase website.</p>
<h2 id="online-video-communication"><a class="header-anchor" href="#online-video-communication">#</a> Online video communication</h2>
<p>During the <a href="https://www.who.int/emergencies/diseases/novel-coronavirus-2019" title="World Health Organization: Coronavirus disease 2019" target="_blank" rel="noopener noreferrer">COVID-19 pandemic of 2019-20<OutboundLink/></a>, various governmental authorities asked their residents to work from home. This resulted in an enormous growth in the use of online video communication, including Zoom.</p>
<p>Because much business-sensitive information is shared during online meetings, this has also caught the attention of cybersecurity experts from all over the world. After research by the experts, it turned out that Zoom is using central servers, hosted by Zoom itself, without using end-to-end encryption. In contrast, Keybase, the company that was acquired by Zoom, is actually offering a <a href="https://book.keybase.io/security#everything-you-store-or-share-on-keybase-is-end-to-end-encrypted" title="Keybase Book: Security" target="_blank" rel="noopener noreferrer">fully end-to-end encrypted platform<OutboundLink/></a>.</p>
<p>Keybase makes it possible to exchange chats and files in a very secure way, without letting third parties have access to this data. In September 2018, Keybase also got a <a href="https://www.nccgroup.com/us/our-research/keybase-protocol-security-review/" title="NCC Group: Keybase Protocol Security Review" target="_blank" rel="noopener noreferrer">security audit<OutboundLink/></a>, to independently test Keybase's security standards.</p>
<h2 id="regular-encryption-versus-end-to-end-encryption"><a class="header-anchor" href="#regular-encryption-versus-end-to-end-encryption">#</a> Regular encryption versus end-to-end encryption</h2>
<p>Zoom and Keybase both use central servers. This means that data between two or more people is transported to a central point, the server(s), where it then gets forwarded to the recipient. Kinda like a parcel service.</p>
<p>Data between Keybase users is encrypted in such a way that this data can only be decrypted by the intended recipient (s), not by others. This principle is called end-to-end encryption. Because data is encrypted in this way, third parties cannot get access to it. Even not if one of the servers were compromised, because the data that is transported is decryptable by the recipient(s) only.</p>
<blockquote>
<p>People can't steal things from you that you don't have.</p>
</blockquote>
<p>Unlike Keybase, Zoom currently does not (yet) use end-to-end encryption. This means that the connection between the users and the servers of Zoom is secured, but that due to the lack of proper end-to-end encryption it is (in theory) possible that Zoom (and third parties) could gain access to the data going over the lines. The data, in this case videoconferences, is sent to Zoom and decrypted there, processed, encrypted again and then sent to the final destination. If Zoom would use end-to-end encryption, it would work in a different way. The data would be encrypted on the side of the sender, in such a way that no one but the intended recipient could decrypt it. The only task left for the Zoom servers, is to relay this data.</p>
<blockquote>
<p>Keep in mind that it is <em>possible</em> that Zoom could peep into your video calls, but that this does not have to mean that they actually do that. But, again, making it impossible by design is the ultimate goal.</p>
</blockquote>
<p>Because Zoom users depend on a central server, adding end-to-end encryption is very important to keep users' data private at all times (even when something gets hacked in future) and to prevent data leaks. Keybase already uses end-to-end encryption, that's why Zoom acquired Keybase. The people at Keybase are now facing the challenge of adding end-to-end encryption to Zoom and make the platform technically more secure.</p>
<h2 id="the-future"><a class="header-anchor" href="#the-future">#</a> The future</h2>
<p>Now that Keybase got acquired by Zoom, it means that Zoom is in full control over the future of Keybase. Although there are some discussions about this on the public Keybase chat, from a personal point of view, my expectation is that it will have a positive outcome. Zoom will improve a lot with the knowledge of the people from Keybase, regarding cyber security practices. I also expect that Zoom will move more towards a more open-source software product and that Keybase will become more popular over time. Whatever the future holds, I will keep an eye on it.</p>
</template>