<template><h1 id="new-3d-printer"><a class="header-anchor" href="#new-3d-printer">#</a> New 3D printer</h1>
<blockquote>
<p>Speaking Dutch? This article is also available in Dutch. <a href="/nl/blog/3d-printer">Don't do moeilijk and read the Dutch version</a>.</p>
</blockquote>
<p>This past week, I bought a 3D printer and received it a few days after ordering it. I was not able to do much with it yet, because the dental surgeon also <tooltip text="I might just sound stupid now">extracted my wisdom teeth</tooltip> a few days ago and I <tooltip text="went AWOL">needed to take some rest</tooltip>. Still, I thought: let's blog again, because 3D printing is very cool.</p>
<p>I had a few requirements for the 3D printer I wanted to have...</p>
<ul>
<li>A decent quality of the printer parts and the resulting prints. Otherwise, I shouldn't be putting any money on it.</li>
<li>Not too expensive, as I'm just a starter in the 3D printing world. When you obtain your driver's license, you usually don't step into a <tooltip text="a luxury supercar">Maserati</tooltip> on your very first trip.</li>
<li>Preferably a printer using open source hardware and/or software. Open source allows others to freely inspect, analyse and improve the product over time.</li>
</ul>
<h2 id="creality-the-business-behind-the-ender-3-pro"><a class="header-anchor" href="#creality-the-business-behind-the-ender-3-pro">#</a> Creality, the business behind the Ender 3 (Pro)</h2>
<p>I bought the <a href="https://www.creality3dofficial.com/products/creality-ender-3-pro-3d-printer" title="Order page of the Ender 3 Pro, a 3D printer made by Creality" target="_blank" rel="noopener noreferrer">Ender 3 Pro<OutboundLink/></a> from Creality, a company from China that builds 3D printers that are using filament and resin as printing material. They are focusing on both hobbyists and the corporate market. Creality became known when they released the Ender 3, a budget 3D printer back in March 2018. This budget 3D printer made 3D printing attractive to home users.</p>
<p>In July 2018, they turned the Ender 3 into a fully open-source 3D printer, which means that all hardware specifications, blueprints, electronic design schemes and (<tooltip text="software that controls the hardware pieces like the motors and acutators, on a low-level basis">firmware</tooltip>-)software were made publicly available, so that anyone with a decent amount of knowledge could improve the product. A very interesting decision!</p>
<hr>
<h1 id="my-very-first-prints"><a class="header-anchor" href="#my-very-first-prints">#</a> My very first prints...</h1>
<p>Although I only received my 3D printer a few days ago, I thought it would be nice to try it out and tell about my very first 3D printings. I was still a bit sick and it also has been quite a while since I worked with 3D software — so instead of creating my own 3D designs, I chose to make the first prints with the pre-supplied files from the SD card.</p>
<h2 id="attempt-1-spaghetti-nom"><a class="header-anchor" href="#attempt-1-spaghetti-nom">#</a> Attempt 1: Spaghetti, nom!</h2>
<p>So, let's tell about my very first attempt. I assembled the 3D printer, chose one of the pre-supplied files and started printing. I just thought... Let's see what happens! The printer began to calibrate itself and it started printing. But instead of printing a model, it started printing 'spaghetti', a term used by 3D print enthusiasts for failed prints. Here's an example of it:</p>
<figure><img src="/assets/img/content/blog/3D-printing-Spaghetti.webp"/><figcaption>A failed 3D print, resulting in typical spaghetti-like creatures. Not my printer, took this one from the web.</figcaption></figure>
<h2 id="attempt-2-not-there-yet"><a class="header-anchor" href="#attempt-2-not-there-yet">#</a> Attempt 2: Not there yet...</h2>
<p>I stopped the printer, leveled the printing bed and put it about 3/10 mm from the nozzle. It's a very precise job, so it takes a while. I gave my printer the instruction to start printing for the second time...</p>
<figure><img src="/assets/img/content/blog/3D-printing-Second-failed-print.webp"/><figcaption>My second attempt. It failed, obviously. Now we have a headless dog. Please don't tell the animal welfare people &#x1f609;</figcaption></figure>
<p>Somehow, my nozzle managed to become stuck in the object during printing, and it literally dragged the entire object over the printing bed. You could see that on the top-front side of the print. Another failed print, such a pity. I almost nailed it!</p>
<h2 id="attempt-3-yes-we-can-smoke-it-in-amsterdam"><a class="header-anchor" href="#attempt-3-yes-we-can-smoke-it-in-amsterdam">#</a> Attempt 3: Yes, we can! (Smoke it in Amsterdam).</h2>
<p>I thought... The nozzle is made out of brass, a metal composition. Metals tend to expand when they become hot, so the inital 3/10 mm I used during the set-up could be way too little when the printer is warmed up. In other words — the nozzle could be too close to the printing bed when it's hot. And eventally, it just gets stuck in the printed model. To fix this, I put the nozzle slightly further away from the printing bed, about 5/10 mm instead of 3/10 mm. I also warmed up the printing bed to 60°C instead of 40°C, to make the model stick a bit better to the printing bed. This resulted in my very first successful print:</p>
<figure><img src="/assets/img/content/blog/3D-printing-First-successful-print.webp"/><figcaption>My first successful 3D print!</figcaption></figure>
<p>Very nice to see! My next step is to picking up 3D modeling again, so that I can make and print my own designs. It is fun to do and it offers many possibilities inside and around the house. If you're looking for inspiration, check out <a href="https://www.thingiverse.com/" title="Makerbot Thingiverse, a website where 3D artists share their creations." target="_blank" rel="noopener noreferrer">Makerbot's Thingiverse<OutboundLink/></a>, a website where other 3D printing enthusiasts share their creations.</p>
<p>3D printing is very cool, and the price-quality ratio of Creality makes it very attractive for '<tooltip text="real geeks">ordinary home users</tooltip>'. Setting up the printer takes a bit more time than you might expect. Keep that in mind. Once everything is set up correctly and your prints stick to the printing bed well enough, it is <tooltip text="still">almost</tooltip> impossible to go wrong. You can make almost anything you want. Gardening pots, pen trays, laptop and screen supports, whatever. The Ender 3 Pro is big enough to print a human skull, and even if you were hitting limits, you can still print your model in multiple parts — so with a little creativity — the possibilities are endless.</p>
<p>I will blog more often about my 3D printing experiences in the near future, because it's a really cool thing to do 👍</p>
</template>