<template><h1 id="docsearch"><a class="header-anchor" href="#docsearch">#</a> docsearch</h1>
<blockquote>
<p>@vuepress/plugin-docsearch</p>
</blockquote>
<p>Integrate <a href="https://docsearch.algolia.com/" target="_blank" rel="noopener noreferrer">Algolia DocSearch<OutboundLink/></a> into VuePress, which can provide search to your documentation site.</p>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>Default theme will add DocSearch to the navbar once you configure this plugin correctly.</p>
<p>This plugin may not be used directly in other themes, so you'd better refer to the documentation of your theme for more details.</p>
</div>
<h2 id="get-search-index"><a class="header-anchor" href="#get-search-index">#</a> Get Search Index</h2>
<p>You need to <a href="https://docsearch.algolia.com/apply/" target="_blank" rel="noopener noreferrer">submit the URL of your site<OutboundLink/></a> to join the DocSearch program. The DocSearch team will send <a href="#apikey">apiKey</a> and <a href="#indexname">indexName</a> to your email once the index is generated. Then you can configure this plugin to enable DocSearch in VuePress.</p>
<p>Alternatively, you can <a href="https://docsearch.algolia.com/docs/run-your-own/" target="_blank" rel="noopener noreferrer">run your own crawler<OutboundLink/></a> to generate the index, and then use your own <a href="#appId">appId</a>, <a href="#apikey">apiKey</a> and <a href="#indexname">indexName</a> to configure this plugin.</p>
<h2 id="options"><a class="header-anchor" href="#options">#</a> Options</h2>
<h3 id="apikey"><a class="header-anchor" href="#apikey">#</a> apiKey</h3>
<ul>
<li>
<p>Type: <code>string</code></p>
</li>
<li>
<p>Required: <code>true</code></p>
</li>
<li>
<p>Details:</p>
<p>The <code>apiKey</code> that you received from the DocSearch team, or generated by yourself.</p>
</li>
<li>
<p>Also see:</p>
<ul>
<li><a href="https://autocomplete-experimental.netlify.app/docs/docsearch-js#apikey" target="_blank" rel="noopener noreferrer">DocSearch &gt; Options &gt; apiKey<OutboundLink/></a></li>
</ul>
</li>
</ul>
<h3 id="indexname"><a class="header-anchor" href="#indexname">#</a> indexName</h3>
<ul>
<li>
<p>Type: <code>string</code></p>
</li>
<li>
<p>Required: <code>true</code></p>
</li>
<li>
<p>Details:</p>
<p>The <code>indexName</code> that you received from the DocSearch team, or generated by yourself.</p>
</li>
<li>
<p>Also see:</p>
<ul>
<li><a href="https://autocomplete-experimental.netlify.app/docs/docsearch-js#indexname" target="_blank" rel="noopener noreferrer">DocSearch &gt; Options &gt; indexName<OutboundLink/></a></li>
</ul>
</li>
</ul>
<h3 id="appid"><a class="header-anchor" href="#appid">#</a> appId</h3>
<ul>
<li>
<p>Type: <code>string</code></p>
</li>
<li>
<p>Details:</p>
<p>Only required if you're <a href="https://docsearch.algolia.com/docs/run-your-own/" target="_blank" rel="noopener noreferrer">running the DocSearch crawler on your own<OutboundLink/></a>. It defines your own application ID.</p>
</li>
<li>
<p>Also see:</p>
<ul>
<li><a href="https://autocomplete-experimental.netlify.app/docs/docsearch-js#appid" target="_blank" rel="noopener noreferrer">DocSearch &gt; Options &gt; appId<OutboundLink/></a></li>
</ul>
</li>
</ul>
<h3 id="searchparameters"><a class="header-anchor" href="#searchparameters">#</a> searchParameters</h3>
<ul>
<li>
<p>Type: <code>Record&lt;string, any&gt;</code></p>
</li>
<li>
<p>Details:</p>
<p>This API parameters of Algolia API.</p>
</li>
<li>
<p>Also see:</p>
<ul>
<li><a href="https://autocomplete-experimental.netlify.app/docs/docsearch-js#searchparameters" target="_blank" rel="noopener noreferrer">DocSearch &gt; Options &gt; searchParameters<OutboundLink/></a></li>
<li><a href="https://www.algolia.com/doc/api-reference/api-parameters/" target="_blank" rel="noopener noreferrer">Algolia &gt; API Parameters<OutboundLink/></a></li>
</ul>
</li>
</ul>
<h3 id="placeholder"><a class="header-anchor" href="#placeholder">#</a> placeholder</h3>
<ul>
<li>
<p>Type: <code>string</code></p>
</li>
<li>
<p>Default: <code>'Search docs'</code></p>
</li>
<li>
<p>Details:</p>
<p>The placeholder attribute of the search input.</p>
</li>
<li>
<p>Also see:</p>
<ul>
<li><a href="https://autocomplete-experimental.netlify.app/docs/docsearch-js#placeholder" target="_blank" rel="noopener noreferrer">DocSearch &gt; Options &gt; placeholder<OutboundLink/></a></li>
</ul>
</li>
</ul>
<h3 id="disableuserpersonalization"><a class="header-anchor" href="#disableuserpersonalization">#</a> disableUserPersonalization</h3>
<ul>
<li>
<p>Type: <code>boolean</code></p>
</li>
<li>
<p>Default: <code>false</code></p>
</li>
<li>
<p>Details:</p>
<p>Whether to disable all personalized features: recent searches, favorite searches, etc.</p>
</li>
<li>
<p>Also see:</p>
<ul>
<li><a href="https://autocomplete-experimental.netlify.app/docs/docsearch-js#disableuserpersonalization" target="_blank" rel="noopener noreferrer">DocSearch &gt; Options &gt; disableUserPersonalization<OutboundLink/></a></li>
</ul>
</li>
</ul>
<h3 id="initialquery"><a class="header-anchor" href="#initialquery">#</a> initialQuery</h3>
<ul>
<li>
<p>Type: <code>string</code></p>
</li>
<li>
<p>Details:</p>
<p>The initial query when the modal opens.</p>
</li>
<li>
<p>Also see:</p>
<ul>
<li><a href="https://autocomplete-experimental.netlify.app/docs/docsearch-js#initialquery" target="_blank" rel="noopener noreferrer">DocSearch &gt; Options &gt; initialQuery<OutboundLink/></a></li>
</ul>
</li>
</ul>
<h3 id="locales"><a class="header-anchor" href="#locales">#</a> locales</h3>
<ul>
<li>
<p>Type: <code>Record&lt;string, DocsearchPluginOptions&gt;</code></p>
</li>
<li>
<p>Details:</p>
<p>Options of this plugin in different locales.</p>
<p>All other options of this plugin are acceptable in locale config.</p>
</li>
<li>
<p>Example:</p>
</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">{</span>
  plugins<span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token punctuation">[</span>
      <span class="token string">'@vuepress/docsearch'</span><span class="token punctuation">,</span>
      <span class="token punctuation">{</span>
        apiKey<span class="token operator">:</span> <span class="token string">'&lt;API_KEY>'</span><span class="token punctuation">,</span>
        indexName<span class="token operator">:</span> <span class="token string">'&lt;INDEX_NAME>'</span><span class="token punctuation">,</span>
        locales<span class="token operator">:</span> <span class="token punctuation">{</span>
          <span class="token string">'/'</span><span class="token operator">:</span> <span class="token punctuation">{</span>
            placeholder<span class="token operator">:</span> <span class="token string">'Search Documentation'</span><span class="token punctuation">,</span>
          <span class="token punctuation">}</span><span class="token punctuation">,</span>
          <span class="token string">'/zh/'</span><span class="token operator">:</span> <span class="token punctuation">{</span>
            placeholder<span class="token operator">:</span> <span class="token string">'搜索文档'</span><span class="token punctuation">,</span>
          <span class="token punctuation">}</span><span class="token punctuation">,</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br></div></div><ul>
<li>Also see:
<ul>
<li><RouterLink to="/src/guide/i18n.html">Guide &gt; I18n</RouterLink></li>
</ul>
</li>
</ul>
<h2 id="styles"><a class="header-anchor" href="#styles">#</a> Styles</h2>
<p>You can customize styles via CSS variables that provided by <a href="https://autocomplete-experimental.netlify.app/docs/docsearch-css" target="_blank" rel="noopener noreferrer">@docsearch/css<OutboundLink/></a>:</p>
<div class="language-css ext-css line-numbers-mode"><pre v-pre class="language-css"><code><span class="token selector">:root</span> <span class="token punctuation">{</span>
  <span class="token property">--docsearch-primary-color</span><span class="token punctuation">:</span> <span class="token function">rgb</span><span class="token punctuation">(</span>84<span class="token punctuation">,</span> 104<span class="token punctuation">,</span> 255<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">--docsearch-text-color</span><span class="token punctuation">:</span> <span class="token function">rgb</span><span class="token punctuation">(</span>28<span class="token punctuation">,</span> 30<span class="token punctuation">,</span> 33<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">--docsearch-spacing</span><span class="token punctuation">:</span> 12px<span class="token punctuation">;</span>
  <span class="token property">--docsearch-icon-stroke-width</span><span class="token punctuation">:</span> 1.4<span class="token punctuation">;</span>
  <span class="token property">--docsearch-highlight-color</span><span class="token punctuation">:</span> <span class="token function">var</span><span class="token punctuation">(</span>--docsearch-primary-color<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">--docsearch-muted-color</span><span class="token punctuation">:</span> <span class="token function">rgb</span><span class="token punctuation">(</span>150<span class="token punctuation">,</span> 159<span class="token punctuation">,</span> 175<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">--docsearch-container-background</span><span class="token punctuation">:</span> <span class="token function">rgba</span><span class="token punctuation">(</span>101<span class="token punctuation">,</span> 108<span class="token punctuation">,</span> 133<span class="token punctuation">,</span> 0.8<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">--docsearch-logo-color</span><span class="token punctuation">:</span> <span class="token function">rgba</span><span class="token punctuation">(</span>84<span class="token punctuation">,</span> 104<span class="token punctuation">,</span> 255<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token comment">/* modal */</span>
  <span class="token property">--docsearch-modal-width</span><span class="token punctuation">:</span> 560px<span class="token punctuation">;</span>
  <span class="token property">--docsearch-modal-height</span><span class="token punctuation">:</span> 600px<span class="token punctuation">;</span>
  <span class="token property">--docsearch-modal-background</span><span class="token punctuation">:</span> <span class="token function">rgb</span><span class="token punctuation">(</span>245<span class="token punctuation">,</span> 246<span class="token punctuation">,</span> 247<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">--docsearch-modal-shadow</span><span class="token punctuation">:</span> inset 1px 1px 0 0 <span class="token function">rgba</span><span class="token punctuation">(</span>255<span class="token punctuation">,</span> 255<span class="token punctuation">,</span> 255<span class="token punctuation">,</span> 0.5<span class="token punctuation">)</span><span class="token punctuation">,</span>
    0 3px 8px 0 <span class="token function">rgba</span><span class="token punctuation">(</span>85<span class="token punctuation">,</span> 90<span class="token punctuation">,</span> 100<span class="token punctuation">,</span> 1<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token comment">/* searchbox */</span>
  <span class="token property">--docsearch-searchbox-height</span><span class="token punctuation">:</span> 56px<span class="token punctuation">;</span>
  <span class="token property">--docsearch-searchbox-background</span><span class="token punctuation">:</span> <span class="token function">rgb</span><span class="token punctuation">(</span>235<span class="token punctuation">,</span> 237<span class="token punctuation">,</span> 240<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">--docsearch-searchbox-focus-background</span><span class="token punctuation">:</span> #fff<span class="token punctuation">;</span>
  <span class="token property">--docsearch-searchbox-shadow</span><span class="token punctuation">:</span> inset 0 0 0 2px <span class="token function">var</span><span class="token punctuation">(</span>--docsearch-primary-color<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token comment">/* hit */</span>
  <span class="token property">--docsearch-hit-height</span><span class="token punctuation">:</span> 56px<span class="token punctuation">;</span>
  <span class="token property">--docsearch-hit-color</span><span class="token punctuation">:</span> <span class="token function">rgb</span><span class="token punctuation">(</span>68<span class="token punctuation">,</span> 73<span class="token punctuation">,</span> 80<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">--docsearch-hit-active-color</span><span class="token punctuation">:</span> #fff<span class="token punctuation">;</span>
  <span class="token property">--docsearch-hit-background</span><span class="token punctuation">:</span> #fff<span class="token punctuation">;</span>
  <span class="token property">--docsearch-hit-shadow</span><span class="token punctuation">:</span> 0 1px 3px 0 <span class="token function">rgb</span><span class="token punctuation">(</span>212<span class="token punctuation">,</span> 217<span class="token punctuation">,</span> 225<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token comment">/* key */</span>
  <span class="token property">--docsearch-key-gradient</span><span class="token punctuation">:</span> <span class="token function">linear-gradient</span><span class="token punctuation">(</span>
    -225deg<span class="token punctuation">,</span>
    <span class="token function">rgb</span><span class="token punctuation">(</span>213<span class="token punctuation">,</span> 219<span class="token punctuation">,</span> 228<span class="token punctuation">)</span> 0%<span class="token punctuation">,</span>
    <span class="token function">rgb</span><span class="token punctuation">(</span>248<span class="token punctuation">,</span> 248<span class="token punctuation">,</span> 248<span class="token punctuation">)</span> 100%
  <span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">--docsearch-key-shadow</span><span class="token punctuation">:</span> inset 0 -2px 0 0 <span class="token function">rgb</span><span class="token punctuation">(</span>205<span class="token punctuation">,</span> 205<span class="token punctuation">,</span> 230<span class="token punctuation">)</span><span class="token punctuation">,</span>
    inset 0 0 1px 1px #fff<span class="token punctuation">,</span> 0 1px 2px 1px <span class="token function">rgba</span><span class="token punctuation">(</span>30<span class="token punctuation">,</span> 35<span class="token punctuation">,</span> 90<span class="token punctuation">,</span> 0.4<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token comment">/* footer */</span>
  <span class="token property">--docsearch-footer-height</span><span class="token punctuation">:</span> 44px<span class="token punctuation">;</span>
  <span class="token property">--docsearch-footer-background</span><span class="token punctuation">:</span> #fff<span class="token punctuation">;</span>
  <span class="token property">--docsearch-footer-shadow</span><span class="token punctuation">:</span> 0 -1px 0 0 <span class="token function">rgb</span><span class="token punctuation">(</span>224<span class="token punctuation">,</span> 227<span class="token punctuation">,</span> 232<span class="token punctuation">)</span><span class="token punctuation">,</span>
    0 -3px 6px 0 <span class="token function">rgba</span><span class="token punctuation">(</span>69<span class="token punctuation">,</span> 98<span class="token punctuation">,</span> 155<span class="token punctuation">,</span> 0.12<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br></div></div><h2 id="components"><a class="header-anchor" href="#components">#</a> Components</h2>
<h3 id="docsearch-1"><a class="header-anchor" href="#docsearch-1">#</a> Docsearch</h3>
<ul>
<li>
<p>Details:</p>
<p>This plugin will register a <code>&lt;Docsearch /&gt;</code> component globally, and you can use it without any props.</p>
<p>Put this component to where you want to place the docsearch button. For example, default theme puts this component to the end of the navbar.</p>
</li>
</ul>
<div class="custom-container tip"><p class="custom-container-title">TIP</p>
<p>This component is mainly used for theme development. You don't need to use it directly in most cases.</p>
</div>
</template>